post/urls.py
from django.urls import path

from . import views

app_name = 'post'
urlpatterns = [
    path('post_list/', views.post_list, name="post_list"),
    path('create_post/', views.create_post, name="create_post"),
    path('post_edit/', views.post_edit, name="post_edit"),
    path('delete_post/<int:pk>/', views.post_delete, name="post_delete"),
    path('<int:post_pk>/thumbnail/<int:image_pk>/', views.thumbnail_view, name='thumbnail'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('profile/', include('user.urls')),
    path('posts/', include('post.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('edit/', views.edit_profile_view, name="edit_profile"),
    path('<str:username>/', views.profile_view, name="profile")
]

user/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="avatars/", blank=True, null=True)
    bio = models.CharField(max_length=200, blank=True)
    gender = models.CharField(max_length=7)
    country = models.CharField(max_length=30, blank=False)
    updated = models.DateTimeField(auto_now=True)
    created =models.DateTimeField(auto_now_add=True)

    @receiver(post_save, sender=settings.AUTH_USER_MODEL)
    def create_or_update_user_profile(instance, **kwargs):
        """
        Automatically create or update user profile after user save.
        """
        Profile.objects.update_or_create(user=instance, defaults={})

    def __str__(self):
        return f"{self.user.username}'s profile"

user/forms.py
from .models import Profile
from django import forms


class EditProfileForm(forms.ModelForm):

    email = forms.EmailField(required=False)
    username = forms.CharField(required=False, max_length=130)
    class Meta:
        model = Profile
        fields = ["avatar", "bio", "gender", "country"]

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)


        self.fields['username'].initial = user.username
        self.fields['email'].initial = user.email

        for field in self.fields.values():
            field.required = False

    def save(self, commit=True):
        profile = super().save(commit=False)
        user = profile.user

        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')
        if username:
            user.username = username
        if email:
            user.email = email

        if commit:
            user.save()
            profile.save()
        return profile

user/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from .models import Profile
from .forms import EditProfileForm

User = get_user_model()

def profile_view(request, username):
    user = get_object_or_404(User, username=username)
    profile = get_object_or_404(Profile, user=user)
    return render(request, 'user/profile.html', {'profile':profile})

@login_required
def edit_profile_view(request):
    profile = get_object_or_404(Profile, user=request.user)

    if request.method == "POST":
        form = EditProfileForm(request.POST, request.FILES, instance=profile, user=request.user)
        if form.is_valid():
            form.save()

            return redirect("user:profile", username=form.cleaned_data['username'])
    else:
        form = EditProfileForm(instance=profile, user=request.user)
    return render(request, 'user/edit_profile.html', {"form":form})

user/templates/user/edit_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile edit</title>
</head>
<body>
<h2> Edit profile </h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Edit</button>
</form>
</body>
</html>

user/templates/user/profile.html
<!doctype html>

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Profile</title>
    <link rel="stylesheet"
    href="https://unpkg.com/swiper/swiper-bundle.min.css"/>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
</head>
<!--width="150" height="150"-->
<body>
{% if profile.avatar %}
<img src="{{ profile.avatar.url }}" alt="avatar" class="avatar">
{% else %}
<img src="{% static 'avatars/baseavatar.png' %}" alt="avatar" width="150" height="150">
{% endif %}
<h2>{{ profile.user.username }}</h2>
<p>{{ profile.bio }}</p>
{% if request.user == profile.user%}
<a href=" {% url 'user:edit_profile'%} ">Edit profile</a>
<a href=" {% url 'post:create_post'%} ">Create post</a>
{% endif %}

{% for post in profile.user.posts.all %}
  <div class="post-block">
    <div class="post-content">
      <p>{{ post.content }}</p>
      {% if request.user == post.author %}
        <a href="{% url 'post:post_delete' pk=post.pk %}">Delete post</a>
      {% endif %}
    </div>
      <div>
          {% with post.images.first as img %}
            {% if img %}
              <img
                src="{% url 'posts:thumbnail' post_pk=post.pk image_pk=img.pk %}"
                alt="Preview"
                style="width:150px; height:150px; object-fit:cover;"
              >
            {% endif %}
          {% endwith %}
    </div>
  </div>
{% endfor %}

<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
<script>
  document.querySelectorAll('.swiper').forEach((el) => {
    new Swiper(el, {
      loop: true,
      navigation: {
        nextEl: el.querySelector('.swiper-button-next'),
        prevEl: el.querySelector('.swiper-button-prev'),
      },
    });
  });
</script>
</body>
</html>