src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('profile/', include('user.urls')),
    path('posts/', include('post.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('edit/', views.edit_profile_view, name="edit_profile"),
    path('<str:username>/', views.profile_view, name="profile")
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}My Site{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

<!-- Кнопка відкриття меню -->
<button id="openSidebar">☰ Menu</button>

<!-- Бокове меню -->
<div id="sidebar">
  <button id="closeSidebar">×</button>
  <ul>
    {% if request.user.is_authenticated %}
      <li><a href="{% url 'user:profile' request.user.username%}">Головна</a></li>
      <li><a href="{% url 'user:profile' request.user.username%}">Профіль</a></li>
      <li><a href="{% url 'user:profile' request.user.username%}">Вийти</a></li>
    {% endif %}
    <!-- і т.д. -->
  </ul>
</div>

<!-- Основний контент сторінки -->
<div id="mainContent">
  {% block content %}
  {% endblock %}
</div>

<script src="{% static 'js/sidebar.js' %}"></script>
</body>
</html>